# Numpy Install

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [5]:
a = np.array([1,2,3])  
print(a)
print(a)
a[2]

[1 2 3]
[1 2 3]


3

In [7]:
a= np.array([[1, 2], [3, 4],[5,6]])
print(a)
a

[[1 2]
 [3 4]
 [5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
print (a.shape)

(3, 2)


In [ ]:
b = a.reshape(2,3)
print(b.shape)
b

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
C= a.reshape(4,4)
C

ValueError: cannot reshape array of size 6 into shape (4,4)

In [ ]:
x = [1,2,3] #list
a = np.asarray(x) 
a

array([1, 2, 3])

In [ ]:
x = (1,2,3) #tuple
a = np.asarray(x) 
a

array([1, 2, 3])

In [ ]:
x = [(1,2,3),(4,5)] #list of tuples 
a = np.asarray(x) 
a

array([(1, 2, 3), (4, 5)], dtype=object)

In [ ]:
x = np.arange(5, dtype = int)
x

array([0, 1, 2, 3, 4])

In [9]:
x = np.arange(10,20,4) 
x

array([10, 14, 18])

In [11]:
#numberline
x = np.linspace(-10,20,12) 
x

array([-10.        ,  -7.27272727,  -4.54545455,  -1.81818182,
         0.90909091,   3.63636364,   6.36363636,   9.09090909,
        11.81818182,  14.54545455,  17.27272727,  20.        ])

In [ ]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a)
print("\n")
print(a[1:])
print("\n")
print(a[:2])
print("\n")
print(a[:3])
print("\n")
print(a[...,0])
print("\n")
print(a[...,1])
print("\n")
print(a[...,2])
print("\n")
print(a[...,1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]


[[3 4 5]
 [4 5 6]]


[[1 2 3]
 [3 4 5]]


[[1 2 3]
 [3 4 5]
 [4 5 6]]


[1 3 4]


[2 4 5]


[3 5 6]


[[2 3]
 [4 5]
 [5 6]]


In [ ]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])  
   
print ('First array:') 
print (a) 
print ('\n') 
   
print ('Second array:') 
print (b) 
print ('\n')
   
print ('First Array + Second Array') 
print (a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


First Array + Second Array
[[ 0.  0.  0.]
 [20. 20. 20.]
 [40. 40. 40.]
 [60. 60. 60.]]


In [ ]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])   
   
print ('First array:') 
print (a) 
print ('\n') 
   
print ('Second array:') 
print (b) 
print ('\n')
   
print ('First Array + Second Array')  #broadcasting
print (a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [ ]:
a = np.arange(0,60,5)
print (a)
a = a.reshape(3,4)
print ('Original array is:')
print (a)
print ('\n')

print ('Transpose of the original array is:')
b = a.T
print (b)
print ('\n')

print ('Sorted in C-style order:')
c = b.copy(order = 'C')
print (c)
for x in np.nditer(c): #ndarray or sequence of array_like. The array(s) to iterate over.
   print (x),

print ('\n')

print ('Sorted in F-style order:')
c = b.copy(order = 'F')
print (c)
for x in np.nditer(c):
   print (x),

[ 0  5 10 15 20 25 30 35 40 45 50 55]
Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Sorted in C-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
20
40
5
25
45
10
30
50
15
35
55


Sorted in F-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
5
10
15
20
25
30
35
40
45
50
55


In [12]:
a = np.array([[1,2],[3,4]]) 

print ('First array:') 
print (a) 
print ('\n')
b = np.array([[5,6],[7,8]]) 

print ('Second array:' )
print (b)
print ('\n'  )
# both the arrays are of same dimensions 

print ('Joining the two arrays along axis 0:' )
print (np.concatenate((a,b), axis =0)) #by default axis =0
print ('\n'  )

print ('Joining the two arrays along axis 1:' )
print (np.concatenate((a,b),axis = 1))

First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]


Joining the two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Joining the two arrays along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


# String Operation

In [ ]:
print (np.char.capitalize('hello world'))
print (np.char.lower('HELLO WORLD')) 
print (np.char.upper('hello world')) 
print (np.char.split ('hello how are you?'))

Hello world
hello world
HELLO WORLD
['hello', 'how', 'are', 'you?']


In [ ]:
print (np.char.strip('ssshok arora','s') )

ssshok aroraaa


In [ ]:
print( np.char.replace ('He is a good boy', 'good', 'bad'))

He is a bad boy


# Statistical Function

In [ ]:
a = np.array([1,2,3,4]) 

print ('Our array is:') 
print (a )
print ('\n'  )

print ('Applying average() function:' )
print (np.average(a) )
print ('\n' ) 

# this is same as mean when weight is not specified 
wts = np.array([4,3,2,1]) 

print ('Applying average() function again:' )
print (np.average(a,weights = wts) )
print ('\n'  )

# Returns the sum of weights, if the returned parameter is set to True. 
print ('Sum of weights' )
print (np.average([1,2,3,4],weights = [4,3,2,1], returned = True))

Our array is:
[1 2 3 4]


Applying average() function:
2.5


Applying average() function again:
2.0


Sum of weights
(2.0, 10.0)


In [ ]:
#a = np.array([[30,65,70,100],[80,95,10,100],[50,90,60,100]]) 
a = np.array([[30,65,70,100],[80,95,10,100],[50,90,60,100],[70,50,40,100]]) 
print ('Our array is:') 
print (a )
print ('\n' ) 

print ('Applying median() function:' )
print (np.median(a)) 
print ('\n' ) 

print ('Applying median() function along axis 0:' )
print (np.median(a, axis = 0) )
print ('\n' ) 
 
print ('Applying median() function along axis 1:') 
print (np.median(a, axis = 1))

Our array is:
[[ 30  65  70 100]
 [ 80  95  10 100]
 [ 50  90  60 100]
 [ 70  50  40 100]]


Applying median() function:
70.0


Applying median() function along axis 0:
[ 60.   77.5  50.  100. ]


Applying median() function along axis 1:
[67.5 87.5 75.  60. ]


In [ ]:
print ("Var:",np.var([1,2,3,4]))
print ("SD:",(np.std([1,2,3,4])))

Var: 1.25
SD: 1.118033988749895


# Pandas

In [14]:
pip install pandas

In [15]:
import pandas as pd

In [16]:
data = np.array(['a','b','c','d'])
s = pd.Series(data)
print (data)
print (s)
s

['a' 'b' 'c' 'd']
0    a
1    b
2    c
3    d
dtype: object


0    a
1    b
2    c
3    d
dtype: object

In [ ]:
data = np.array(['a','b','c','d'])
s = pd.Series(data,index=[100,101,102,103])
print (s)
#retrieve the elements
print()
print (s[101])
#retrieve the first three element
print()
print (s[:3])
#retrieve from nth element
print()
print (s[2:])

100    a
101    b
102    c
103    d
dtype: object

b

100    a
101    b
102    c
dtype: object

102    c
103    d
dtype: object


# Dataframe

In [ ]:
df = pd.DataFrame()
print (df)

Empty DataFrame
Columns: []
Index: []


In [ ]:
data = [1,2,3,4,5]
df = pd.DataFrame(data)
print (df)
df

   0
0  1
1  2
2  3
3  4
4  5


0
0  1
1  2
2  3
3  4
4  5

In [19]:
data = [['Alex',10,25000],['Bob',12,30000],['Clarke',13,20000],['John',20,50000]]

df = pd.DataFrame(data,columns=['Name','Age','Salary'])
df

[['Alex', 10, 25000], ['Bob', 12, 30000], ['Clarke', 13, 20000], ['John', 20, 50000]]


Name  Age  Salary
0    Alex   10   25000
1     Bob   12   30000
2  Clarke   13   20000
3    John   20   50000

In [ ]:
data = [['Alex',10],['Bob',12],['Clarke',13],['John',]]
df = pd.DataFrame(data,columns=['Name','Age'])
df

Name   Age
0    Alex  10.0
1     Bob  12.0
2  Clarke  13.0
3    John   NaN

In [ ]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
   'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

df = pd.DataFrame(d)

df

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [ ]:
# Adding a new column to an existing DataFrame object with column label by passing new series

print ("Adding a new column by passing as Series:")
df['three']=pd.Series([10,20,30],index=['a','b','c'])
df



Adding a new column by passing as Series:


one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN

In [ ]:
print ("Adding a new column by passing as Series:")
df['three']=pd.Series([10,20,30,40],index=['a','b','c','d'])
df

Adding a new column by passing as Series:


one  two  three
a  1.0    1     10
b  2.0    2     20
c  3.0    3     30
d  NaN    4     40

In [ ]:
print ("Adding a new column by passing as Series:")
df['three']=pd.Series([10,20,30,40],index=['d','c','b','a'])
df

Adding a new column by passing as Series:


one  two  three
a  1.0    1     40
b  2.0    2     30
c  3.0    3     20
d  NaN    4     10

In [ ]:
print ("Adding a new column using the existing columns in DataFrame:")
df['four']=df['one']+df['three']
df

Adding a new column using the existing columns in DataFrame:


one  two  three  four
a  1.0    1     40  41.0
b  2.0    2     30  32.0
c  3.0    3     20  23.0
d  NaN    4     10   NaN

In [ ]:
del df['one']
df

two  three  four
a    1   10.0  11.0
b    2   20.0  22.0
c    3   30.0  33.0
d    4    NaN   NaN

In [ ]:
del df['three']
df

two  four
a    1  11.0
b    2  22.0
c    3  33.0
d    4   NaN

In [ ]:
df

two  four
a    1  11.0
b    2  22.0
c    3  33.0
d    4   NaN

In [ ]:
df = df.drop(0)

KeyError: '[0] not found in axis'

In [ ]:
df = df.drop('b')
df

two  four
a    1  11.0
c    3  33.0
d    4   NaN

# Merage and Join

In [ ]:
left = pd.DataFrame({
   'id':[1,2,3,4,5],
   'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
   'subject_id':['sub1','sub2','sub4','sub6','sub5']})
right = pd.DataFrame(
   {'id':[1,2,3,4,5],
   'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
   'subject_id':['sub2','sub4','sub3','sub6','sub5']})


   id    Name subject_id
0   1    Alex       sub1
1   2     Amy       sub2
2   3   Allen       sub4
3   4   Alice       sub6
4   5  Ayoung       sub5
   id   Name subject_id
0   1  Billy       sub2
1   2  Brian       sub4
2   3   Bran       sub3
3   4  Bryce       sub6
4   5  Betty       sub5


In [ ]:
left

id    Name subject_id
0   1    Alex       sub1
1   2     Amy       sub2
2   3   Allen       sub4
3   4   Alice       sub6
4   5  Ayoung       sub5

In [ ]:
right

id   Name subject_id
0   1  Billy       sub2
1   2  Brian       sub4
2   3   Bran       sub3
3   4  Bryce       sub6
4   5  Betty       sub5

In [ ]:
pd.merge(left,right,on='id')

id  Name_x subject_id_x Name_y subject_id_y
0   1    Alex         sub1  Billy         sub2
1   2     Amy         sub2  Brian         sub4
2   3   Allen         sub4   Bran         sub3
3   4   Alice         sub6  Bryce         sub6
4   5  Ayoung         sub5  Betty         sub5

In [ ]:
pd.merge(left, right, how='outer', on='subject_id')

id_x  Name_x subject_id  id_y Name_y
0   1.0    Alex       sub1   NaN    NaN
1   2.0     Amy       sub2   1.0  Billy
2   3.0   Allen       sub4   2.0  Brian
3   4.0   Alice       sub6   4.0  Bryce
4   5.0  Ayoung       sub5   5.0  Betty
5   NaN     NaN       sub3   3.0   Bran

In [ ]:
pd.merge(left, right, on='subject_id', how='inner')

id_x  Name_x subject_id  id_y Name_y
0     2     Amy       sub2     1  Billy
1     3   Allen       sub4     2  Brian
2     4   Alice       sub6     4  Bryce
3     5  Ayoung       sub5     5  Betty